# Generated by Django 3.1.6 on 2021-02-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=150)),
                ('sign_up_date', models.DateField()),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
