# Generated by Django 3.1.6 on 2021-02-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_custinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinfo',
            name='addres',
            field=models.CharField(default='', max_length=200),
        ),
    ]
