# Generated by Django 3.1.6 on 2021-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_custinfo_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinfo',
            name='loginstate',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
