# Generated by Django 3.1.6 on 2021-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_custinfo_loginstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinfo',
            name='gender',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
