# Generated by Django 3.1.6 on 2021-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_custinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinfo',
            name='image',
            field=models.ImageField(default='', upload_to='customer/images'),
        ),
    ]
