# Generated by Django 3.1.6 on 2021-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
