# Generated by Django 3.1.6 on 2021-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_custom_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_order',
            name='accept_status',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_order',
            name='feedback',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_order',
            name='work_description',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_order',
            name='work_done_status',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
