# Generated by Django 3.1.6 on 2021-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20210216_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_order',
            name='end_date',
            field=models.DateField(default=''),
        ),
    ]
