# Generated by Django 3.1.6 on 2021-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20210216_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_order',
            name='accept_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_order',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_order',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
