# Generated by Django 3.1.6 on 2021-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20210216_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=150)),
                ('serviceman_email', models.CharField(default='none', max_length=150)),
                ('accept_status', models.CharField(default='None', max_length=50)),
                ('work_done_status', models.CharField(default='None', max_length=50)),
                ('feedback', models.CharField(default='None', max_length=50)),
                ('request_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('accept_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_address', models.CharField(default='', max_length=500)),
                ('work_description', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
