# Generated by Django 3.1.6 on 2021-02-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_order',
            name='work',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
