# Generated by Django 3.1.6 on 2021-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_custom_order_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_order',
            name='customer_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='custom_order',
            name='customer_phone',
            field=models.IntegerField(default=9774546207),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_order',
            name='serviceman_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='custom_order',
            name='serviceman_phone',
            field=models.IntegerField(default=9774546207),
            preserve_default=False,
        ),
    ]
