# Generated by Django 3.1.6 on 2021-02-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
