# Generated by Django 3.1.6 on 2021-02-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceinfo',
            old_name='secondary_word',
            new_name='secondary_work',
        ),
    ]
