# Generated by Django 3.1.6 on 2021-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0002_auto_20210214_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='carpenter',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='cleaning',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='electrecian',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='kitchen',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='loginstate',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='plumber',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='technecian',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
