# Generated by Django 3.1.6 on 2021-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceman', '0003_auto_20210215_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='carpenter',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='cleaning',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='electrecian',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='kitchen',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='plumber',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='technecian',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
